@startuml

[*] --> 投稿一覧

state 投稿の選別 {

投稿一覧 --> 投稿カテゴリ別
投稿一覧 --> 投稿月別

}

投稿一覧 ---> ラウンジ募集
投稿一覧 ---> トレモ風景

投稿一覧 ---> 投稿詳細

投稿一覧 --> ログイン
ラウンジ募集 --> ログイン
トレモ風景 --> ログイン
投稿詳細 --> ログイン
投稿カテゴリ別 --> ログイン
投稿月別 --> ログイン

投稿一覧 : /
投稿カテゴリ別 :/?category_id=@
投稿月別 :/?year=yyyy&month=MM

ラウンジ募集 : /sf5lounge
トレモ風景 : /daily_post
投稿詳細 : /article/{id?}

ログイン : /login
@enduml
