@startuml

[*] -> 投稿一覧



投稿一覧 --> ラウンジ募集
投稿一覧 --> トレモ風景

投稿一覧 --> 投稿詳細
投稿一覧 --> コメント一覧
投稿一覧 --> ドリフト


コメント一覧:/comment/list

投稿一覧 : /

ドリフト:/drift_post

ラウンジ募集 : /sf5lounge
トレモ風景 : /daily_post
投稿詳細 : /article/{id?}


@enduml
